<a href="https://colab.research.google.com/github/jsm-UOC/tensorflowCourse/blob/main/FirstCourseTF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **First Tensorflow Program**
### Import Tensorflow

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.12.0


# Difference between types of Tensors

## Scalar dim = 0

In [ ]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
scalar.ndim

0

## Vector dim = 1

In [ ]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

## Matrix dim = 2

In [ ]:
matrix = tf.constant([[10,7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
another_matrix = tf.constant([[10.,7.],
                             [3.,2.],
                             [8.,9.]], dtype = tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

## Tensor dim = 3

In [ ]:
tensor = tf.constant([[[1,2,3],
                       [4,5,6],
                       [7,8,9]],
                      [[11,22,33],
                       [44,55,66],
                       [77,88,99]]])
tensor

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 22, 33],
        [44, 55, 66],
        [77, 88, 99]]], dtype=int32)>

# Difference between Variables and Constants

In [ ]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:

#changeable_tensor[0] = 7
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [ ]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

# Creating Tensors

## Tensors of 1s and 0s

In [ ]:
tf.ones([10,2,3])

<tf.Tensor: shape=(10, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [ ]:
tf.zeros(shape=(1))

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>

## Tensors from Numpy Arrays

In [ ]:
import numpy as np

numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A, shape=(2, 3, 4))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [ ]:
A.ndim

3

# Random Tensors and Shuffling

In [ ]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [ ]:
not_shuffled = tf.constant([[10,2],
                            [3,5],
                            [1,7]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  2],
       [ 3,  5],
       [ 1,  7]], dtype=int32)>

# Manipulating Tensors
## Getting Info from Tensors

In [ ]:
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
print("Datatype of every element: ", rank_4_tensor.dtype)
print("Number of dimensions: ", rank_4_tensor.ndim)
print("Shape of the tensor: ", rank_4_tensor.shape)
print("Elements along the 0 axis: ", rank_4_tensor.shape[0])
print("Elements along the last axis: ", rank_4_tensor.shape[-1])
print("Total number of elements in out tensor: ", tf.size(rank_4_tensor))



Datatype of every element:  <dtype: 'float32'>
Number of dimensions:  4
Shape of the tensor:  (2, 3, 4, 5)
Elements along the 0 axis:  2
Elements along the last axis:  5
Total number of elements in out tensor:  tf.Tensor(120, shape=(), dtype=int32)


## Indexing and Slicing

In [ ]:
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_2_tensor = tf.constant([[10,7],
                             [3,4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [ ]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

## Reshaping Tensors

In [ ]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

### Add new dimension

In [ ]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

### Change the shape

In [ ]:
tf.reshape(rank_2_tensor, shape=(2,2,1))

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
tf.reshape(rank_2_tensor, shape=(4))

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([10,  7,  3,  4], dtype=int32)>

### Squeeze a tensor

In [ ]:
tf.random.set_seed(42)
G = tf.random.uniform(shape=[1, 1, 1, 1, 50])
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

## Tensor operations


### Python built-in operations

In [ ]:
tensor = tf.constant([[10,7],
                      [3,4]])
tensor + 10, tensor * 10, tensor - 10

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[20, 17],
        [13, 14]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  70],
        [ 30,  40]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 0, -3],
        [-7, -6]], dtype=int32)>)

**Element-wise multiplication**

In [ ]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

**Matrix multiplication**

In [ ]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

### Tensorflow built-in operations

In [ ]:
tf.add(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

**Element-wise multiplication**

In [ ]:
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
tf.multiply(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

**Matrix multiplication**

In [ ]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

**Squaring, log, square root, ...**

In [ ]:
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Matrix Multiplication

In [ ]:
X = tf.constant([[1,2],
                [3,4],
                [5,6]])
Y = tf.constant([[11,22],
                [33,44],
                [55,66]])

In [ ]:
tf.matmul(X,tf.transpose(Y)), tf.matmul(tf.transpose(X),Y)

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 55, 121, 187],
        [121, 275, 429],
        [187, 429, 671]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[385, 484],
        [484, 616]], dtype=int32)>)

In [ ]:
tf.matmul(X,tf.reshape(Y, shape=(2,3))), tf.matmul(tf.reshape(X, shape=(2,3)),Y)

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 99, 132, 165],
        [209, 286, 363],
        [319, 440, 561]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[242, 308],
        [539, 704]], dtype=int32)>)

### Dot Product

In [ ]:
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[11, 22],
        [33, 44],
        [55, 66]], dtype=int32)>)

In [ ]:
tf.tensordot(X, tf.transpose(Y), axes=1), tf.tensordot(tf.transpose(X), Y, axes=1)

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 55, 121, 187],
        [121, 275, 429],
        [187, 429, 671]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[385, 484],
        [484, 616]], dtype=int32)>)

## Changing DataTypes

In [ ]:
B = tf.constant([1.7, 1.4])
B.dtype

tf.float32

In [ ]:
C = tf.constant([7, 10])
C.dtype

tf.int32

In [ ]:
D = tf.cast(B, dtype=tf.float16)
D

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 1.4], dtype=float16)>

In [ ]:
E = tf.cast(C, dtype=tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

In [ ]:
E_float16 = tf.cast(E, dtype=tf.float16)
E_float16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

# Aggreation functions on Tensors

In [ ]:
D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [ ]:
E = tf.constant(np.random.randint(0,100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([23, 60, 74, 29, 24, 83, 93, 29, 72,  9, 11, 71, 63, 91, 72, 18, 80,
       23, 70, 56, 47, 66, 14, 99,  8, 34, 57, 54, 68, 31, 68, 43, 39, 15,
       38, 60, 62, 48, 44, 49, 57, 56, 56, 64, 73, 59, 96,  8, 35, 23])>

In [ ]:
tf.reduce_min(E), tf.reduce_max(E)

(<tf.Tensor: shape=(), dtype=int64, numpy=8>,
 <tf.Tensor: shape=(), dtype=int64, numpy=99>)

In [ ]:
tf.reduce_sum(E), tf.reduce_mean(E)

(<tf.Tensor: shape=(), dtype=int64, numpy=2522>,
 <tf.Tensor: shape=(), dtype=int64, numpy=50>)

In [ ]:
tf.math.reduce_variance(tf.cast(E,dtype=tf.float32)), tf.math.reduce_std(tf.cast(E,dtype=tf.float32))

(<tf.Tensor: shape=(), dtype=float32, numpy=601.6464>,
 <tf.Tensor: shape=(), dtype=float32, numpy=24.528482>)

In [ ]:
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
tf.argmin(F), tf.argmax(F)

(<tf.Tensor: shape=(), dtype=int64, numpy=16>,
 <tf.Tensor: shape=(), dtype=int64, numpy=42>)

In [ ]:
F[tf.argmin(F)] == tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

# One-hot Encoding Tensors

In [ ]:
some_list = [0, 1, 2, 3]
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
tf.one_hot(some_list, depth=4, on_value="YES", off_value="NO")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'YES', b'NO', b'NO', b'NO'],
       [b'NO', b'YES', b'NO', b'NO'],
       [b'NO', b'NO', b'YES', b'NO'],
       [b'NO', b'NO', b'NO', b'YES']], dtype=object)>

# Tensors and NumPy

In [ ]:
 J = tf.constant(np.array([3., 7., 10.]))
 J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

# Finding access to GPUs

In [ ]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Wed Apr  5 12:16:16 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   65C    P0    30W /  70W |    375MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

# Exercises 1

In [ ]:
sca1 = tf.constant([1])
vec1 = tf.constant([1,2,3])
mat1 = tf.constant([[1,2],
                      [3,4]])
ten1 = tf.constant([[[1,2,3],
                     [11,22,33]],
                    [[4,5,6],
                     [44,55,66]]])
sca1, vec1, mat1, ten1

(<tf.Tensor: shape=(1,), dtype=int32, numpy=array([1], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [11, 22, 33]],
 
        [[ 4,  5,  6],
         [44, 55, 66]]], dtype=int32)>)

In [ ]:
sca1.shape, sca1.ndim, tf.size(sca1)

(TensorShape([1]), 1, <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [ ]:
vec1.shape, vec1.ndim, tf.size(vec1)

(TensorShape([3]), 1, <tf.Tensor: shape=(), dtype=int32, numpy=3>)

In [ ]:
mat1.shape, mat1.ndim, tf.size(mat1)

(TensorShape([2, 2]), 2, <tf.Tensor: shape=(), dtype=int32, numpy=4>)

In [ ]:
ten1.shape, ten1.ndim, tf.size(ten1)

(TensorShape([2, 2, 3]), 3, <tf.Tensor: shape=(), dtype=int32, numpy=12>)

In [ ]:
ten2 = tf.random.uniform([5,300])
ten3 = tf.random.uniform([5,300])
ten2, ten3

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.95831835, 0.01680839, 0.3156035 , ..., 0.67105925, 0.76730955,
         0.20125735],
        [0.09921694, 0.02475083, 0.47242153, ..., 0.9631474 , 0.34333456,
         0.8129494 ],
        [0.08817983, 0.9311962 , 0.2293179 , ..., 0.41450226, 0.008304  ,
         0.02438807],
        [0.54814565, 0.37019622, 0.5272658 , ..., 0.8656951 , 0.19644582,
         0.5959221 ],
        [0.8964087 , 0.15288067, 0.3360591 , ..., 0.5725572 , 0.4094149 ,
         0.40059018]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.43555546, 0.52486527, 0.49674678, ..., 0.00552487, 0.3156761 ,
         0.22303641],
        [0.93881905, 0.02025807, 0.8929347 , ..., 0.47184265, 0.93879664,
         0.27382708],
        [0.8537835 , 0.287457  , 0.57827055, ..., 0.22605908, 0.62864304,
         0.28893173],
        [0.83130777, 0.13316286, 0.4270022 , ..., 0.96334374, 0.81353974,
         0.47423255],
        [0.20213

In [ ]:
tf.matmul(tf.transpose(ten2),ten3), tf.matmul(ten2, tf.transpose(ten3))

(<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
 array([[1.2227077 , 0.74635607, 1.7006097 , ..., 1.4339572 , 1.175743  ,
         0.89622366],
        [1.164247  , 0.35069013, 0.87213147, ..., 0.7211163 , 0.9626345 ,
         0.5182214 ],
        [1.2830186 , 0.3649675 , 1.2553747 , ..., 1.0970403 , 1.2207333 ,
         0.6547262 ],
        ...,
        [2.385793  , 0.6975059 , 2.3462267 , ..., 1.9184322 , 2.258906  ,
         1.1799669 ],
        [0.9096889 , 0.5035559 , 1.1650587 , ..., 0.738209  , 0.8568732 ,
         0.5296512 ],
        [1.4480615 , 0.2723792 , 1.4747108 , ..., 1.3369259 , 1.4514141 ,
         0.7224447 ]], dtype=float32)>,
 <tf.Tensor: shape=(5, 5), dtype=float32, numpy=
 array([[73.45296 , 74.09731 , 74.092186, 73.01437 , 73.156876],
        [74.90098 , 75.27091 , 77.775635, 74.37875 , 74.90591 ],
        [83.04034 , 79.46228 , 82.300026, 80.63679 , 78.7219  ],
        [76.86667 , 76.41696 , 79.00328 , 77.386116, 77.40252 ],
        [76.20902 , 74.707855, 

In [ ]:
tf.tensordot(tf.reshape(ten2, shape=(300,5)),ten3, axes=1), tf.tensordot(ten2, tf.reshape(ten3, shape=(300,5)), axes=1)

(<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
 array([[0.9802571 , 0.7294286 , 1.4205271 , ..., 0.9038221 , 0.8692382 ,
         0.68044996],
        [1.0373178 , 0.63988084, 1.3689739 , ..., 0.9168338 , 0.9317551 ,
         0.66094613],
        [1.4492459 , 0.6989448 , 1.1103034 , ..., 0.96827394, 1.2712358 ,
         0.7348511 ],
        ...,
        [1.3526613 , 0.5245875 , 1.4912858 , ..., 1.3427961 , 1.2327067 ,
         0.81545055],
        [2.5152001 , 0.9907487 , 2.2166743 , ..., 1.6714772 , 2.205762  ,
         1.2145045 ],
        [1.6495492 , 0.4251736 , 1.6096195 , ..., 1.2158446 , 1.5275803 ,
         0.76404625]], dtype=float32)>,
 <tf.Tensor: shape=(5, 5), dtype=float32, numpy=
 array([[73.18031 , 74.87461 , 74.44004 , 71.073265, 68.95417 ],
        [74.776695, 75.75687 , 77.546814, 72.14329 , 73.153564],
        [81.712105, 81.39893 , 78.34574 , 76.58476 , 80.466705],
        [79.061226, 77.07333 , 76.17834 , 74.92463 , 75.26428 ],
        [77.532326, 76.81462 , 

In [ ]:
ten4 = tf.random.uniform([224, 224, 3])
ten4

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.14241445, 0.40161622, 0.33360183],
        [0.6816542 , 0.69087017, 0.22069418],
        [0.61336195, 0.9588975 , 0.3314948 ],
        ...,
        [0.21534526, 0.8758553 , 0.90849984],
        [0.913136  , 0.3300879 , 0.21957576],
        [0.294909  , 0.51060224, 0.41247094]],

       [[0.24516141, 0.0526433 , 0.8009639 ],
        [0.39559937, 0.91123044, 0.66148484],
        [0.62018025, 0.13185847, 0.2584139 ],
        ...,
        [0.69155025, 0.35061288, 0.7918345 ],
        [0.71887565, 0.13187587, 0.6776898 ],
        [0.91522217, 0.72013485, 0.5736792 ]],

       [[0.32997262, 0.01919758, 0.7673421 ],
        [0.37867343, 0.09564745, 0.07906318],
        [0.7100911 , 0.934427  , 0.5622425 ],
        ...,
        [0.8063401 , 0.53997624, 0.9590297 ],
        [0.7728716 , 0.5758432 , 0.53311133],
        [0.00398016, 0.15231979, 0.6468185 ]],

       ...,

       [[0.3400538 , 0.40921474, 0.04457414],
        [0.86

In [ ]:
tf.reduce_min(ten4[0])

<tf.Tensor: shape=(), dtype=float32, numpy=0.00034153461>

In [ ]:
ten5 = tf.random.uniform([1, 224, 224, 3])
ten5, tf.squeeze(ten5)

(<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
 array([[[[0.2046014 , 0.82478166, 0.81674874],
          [0.57813525, 0.72301936, 0.9893687 ],
          [0.33879173, 0.4470011 , 0.24898088],
          ...,
          [0.574314  , 0.6185826 , 0.4371407 ],
          [0.45086288, 0.673488  , 0.19694173],
          [0.7261505 , 0.4120711 , 0.11013401]],
 
         [[0.6134424 , 0.91840196, 0.6838045 ],
          [0.89331627, 0.67425346, 0.60953534],
          [0.36227953, 0.00483751, 0.22489178],
          ...,
          [0.84603393, 0.24309051, 0.18531716],
          [0.5195565 , 0.6304064 , 0.7182379 ],
          [0.22715592, 0.4978919 , 0.8341614 ]],
 
         [[0.15624535, 0.1719867 , 0.6037985 ],
          [0.86916864, 0.16423154, 0.9619628 ],
          [0.37755537, 0.9332715 , 0.8822973 ],
          ...,
          [0.82203424, 0.9220053 , 0.45980155],
          [0.66036093, 0.23616183, 0.37692404],
          [0.05016053, 0.35180223, 0.3742    ]],
 
         ...,
 
       

In [ ]:
ten6 = tf.constant([1,3,2,4,4,5,0,6,7,3])
ten6, tf.argmin(ten6)

(<tf.Tensor: shape=(10,), dtype=int32, numpy=array([1, 3, 2, 4, 4, 5, 0, 6, 7, 3], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int64, numpy=6>)

In [ ]:
tf.one_hot(ten6, depth=8)

<tf.Tensor: shape=(10, 8), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0., 0., 0.]], dtype=float32)>